import { type ClientSchema, a, defineData } from '@aws-amplify/backend';

/**
 * Data schema for Bible Bowl scoring.
 *
 * Models:
 *  - GameState (singleton, id='SINGLETON'): tracks the current question number
 *  - Team: a church competing in the bowl
 *  - Score: a single question's score (0–3) for one team
 *  - OnboardingToken: single-use QR-code token that bootstraps a scorekeeper session
 *
 * Auth summary:
 *  - Guests (viewers) and authenticated users can READ everything.
 *  - Admins can CRUD everything.
 *  - Scorekeepers create Score records via the /api/scorekeeper/score route,
 *    which validates the session and game state before writing via the API key.
 *    Scorekeepers cannot update past scores — the server route only creates.
 *  - `allow.publicApiKey()` on Team, OnboardingToken, and Score is used exclusively
 *    by Next.js server routes after validating the caller's identity in the handler.
 *    The API key is public in amplify_outputs.json but write operations are
 *    enforced by route-handler logic (admin session checks / token validation).
 */
const schema = a.schema({
  GameState: a
    .model({
      currentQuestion: a.integer().required(),
      // Explicit scoring gate. true = scoring open; false = closed (e.g. end game pressed).
      // Null/absent is treated as open by clients to preserve backward-compat with
      // records created before this field was added.
      scoringOpen: a.boolean(),
    })
    .authorization((allow) => [
      allow.guest().to(['read']),
      allow.authenticated().to(['read']),
      allow.groups(['Admins']).to(['create', 'read', 'update', 'delete']),
    ]),

  Team: a
    .model({
      name: a.string().required(),
      scorekeeperUserId: a.string(),
      scorekeeperEmail: a.string(),
      displayOrder: a.integer(),
      groupType: a.enum(['Teen', 'PreTeen', 'Adult']),
    })
    .authorization((allow) => [
      allow.guest().to(['read']),
      allow.authenticated().to(['read']),
      allow.groups(['Admins']).to(['create', 'read', 'update', 'delete']),
      // Server routes (claim + admin user creation) use the API key
      // after validating the caller's Cognito JWT in the route handler.
      allow.publicApiKey().to(['read', 'update']),
    ]),

  Score: a
    .model({
      teamId: a.string().required(),
      questionNumber: a.integer().required(),
      points: a.integer().required(),
    })
    // Secondary index for efficient per-team lookups
    .secondaryIndexes((index) => [index('teamId').sortKeys(['questionNumber']).name('byTeamId')])
    .authorization((allow) => [
      allow.guest().to(['read']),
      allow.authenticated().to(['read']),
      allow.groups(['Admins']).to(['create', 'read', 'update', 'delete']),
      // Scorekeepers create scores via the /api/scorekeeper/score route, which
      // validates session + game state before writing. The API key is the write
      // credential; direct owner-based client writes are intentionally removed.
      allow.publicApiKey().to(['create', 'read']),
    ]),

  /**
   * QR-code onboarding tokens. One token per team, generated by the admin
   * before the event. Each token encodes a deep link the scorekeeper scans to
   * get a passwordless Cognito session bound to their team.
   *
   * tokenId is the UUID encoded in the QR code's deep link and serves as the
   * primary key for O(1) lookup during token exchange.
   */
  OnboardingToken: a
    .model({
      tokenId: a.string().required(),
      teamId: a.string().required(),
      status: a.enum(['UNUSED', 'CONSUMED']),
      consumedAt: a.string(),
      expiresAt: a.string(),
      batchId: a.string(),
    })
    .identifier(['tokenId'])
    .authorization((allow) => [
      allow.groups(['Admins']).to(['create', 'read', 'update', 'delete']),
      // Server routes (generate, exchange, end-game) use the API key after
      // enforcing admin/token validation themselves in the handler.
      allow.publicApiKey().to(['create', 'read', 'update', 'delete']),
    ]),
});

export type Schema = ClientSchema<typeof schema>;

/** Constant used throughout the app to identify the singleton GameState record. */
export const GAME_STATE_ID = 'SINGLETON';

export const data = defineData({
  schema,
  authorizationModes: {
    // Identity Pool (IAM) is the default — supports guest (unauthenticated) reads
    // for the public leaderboard without requiring a login.
    defaultAuthorizationMode: 'identityPool',
    // API key used by Next.js server routes for Team updates (claim + admin ops).
    apiKeyAuthorizationMode: { expiresInDays: 365 },
  },
});
